Algoritmo "semnome"
//  
//  
// projeto novo contas com informações externas
Var
// varias de memória
 aluno,professor: caracter
 nota1,nota2,media:real
 
 Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("nome do aluno")
leia (aluno)
escreval ("nome professor")
leia(professor)
escreval("nota 1")
leia(nota1)
escreval("nota 2")
leia(nota2)

media<-(nota1+nota2)/2
escreval("a media resultara em",media)

Fimalgoritmo