Algoritmo "semnome"
// 
//  
// Descrição   : atividade 7 temperatura
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
 temperatura:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("qual a temperatura ambiente:")
leia (temperatura)
se (temperatura>=25) entao
escreva ("está muito quente!")
fimse
se (temperatura<25) entao
escreva ("está agradavel")
fimse

Fimalgoritmo