Algoritmo "semnome"
// 
//  
// Descrição   : par ou impar atividade 5
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
numero:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Escreva seu número: ")
leia (numero)

se (numero mod 2 = 0) entao
escreva ("Esse número é par")
senao
escreva ("esse numero é impar")
fimse



Fimalgoritmo
